#!/bin/bash

curr_dir=$(dirname $0)

if [ -z "${XMD_ROOT_FILE}" ]; then
    filename="LIT.md"
else
    filename="${XMD_ROOT_FILE}"
fi

#  NOTE: don't try this:
#
#   pandoc -f markdown -t json ${filename} | python3 ${curr_dir}/xmd.py $@
#
#  For some reason piping messes up my ability to spawn processes for the python script. I get
#    this error: "the input device is not a TTY"
#
#  So, I have to pass the json as an argument.

pandoc -f markdown -t json "${filename}" | python3 -m json.tool > LIT.json
python3 ${curr_dir}/xmd.py LIT.json $@
