#!/bin/bash

curr_dir=$(dirname $0)

if [ -z "${XMD_ROOT_FILE}" ]; then
    if [ "$#" -eq 0 ]; then
        echo "Missing Filename"
        exit 1
    fi

    filename=$1
    shift
else
    filename="${XMD_ROOT_FILE}"
fi

cmd="pandoc -f markdown -t json ${filename} | python3 ${curr_dir}/xmd.py $@"

if [ "$#" -eq 0 ] || [ "$1" != "-i" ]; then
    eval "$cmd"
else
    # if this is a "run" command, then evaluate the command being returned
    eval "$(eval "$cmd")"
fi
